#[derive(Clone, Copy)]
pub enum LoadsAndStores {
    CompareAndSwapPair,
    AdvancedSIMDLoadStoreMultipleStructures,
    AdvancedSIMDLoadStoreMultipleStructuresPostIndexed,
    Unallocated0,
    AdvancedSIMDLoadStoreSingleStructure,
    AdvancedSIMDLoadStoreSingleStructurePostIndexed,
    Unallocated1,
    Unallocated2,
    Unallocated3,
    Unallocated4,
    Unallocated5,
    LoadStoreMemoryTags,
    LoadStoreExclusivePair,
    Unallocated6,
    LoadStoreExclusiveRegister,
    LoadStoreOrdered,
    CompareAndSwap,
    LDAPRSTLRUnscalaedImmediate,
    LoadRegisterLiteral,
    MemoryCopyAndMemorySet,
    LoadStoreNoAllocatePairOffset,
    LoadStoreRegisterPairPostIndexed,
    LoadStoreRegisterPairOffset,
    LoadStoreRegisterPairPreIndexed,
    LoadStoreRegisterUnscalaedImmediate,
    LoadStoreRegisterImmediatePostIndexed,
    LoadStoreRegisterUnprivileged,
    LoadStoreRegisterImmediatePreIndexed,
    AtomicMemoryOperations,
    LoadStoreRegisterRegisterOffset,
    LoadStoreRegisterPac,
    LoadStoreRegisterUnsignedImmediate,
}

#[derive(Clone, Copy)]
pub enum LoadStoreRegisterUnsignedImmediate {
    Unallocated0,
    STRBImmediate,
    LDRBImmediate,
    LDRSBImmediate64,
    LDRSBImmediate32,
    STRImmediateSIMDFP8,
    LDRImmediateSIMDFP8,
    STRImmediateSIMDFP128,
    LDRImmediateSIMDFP128,
    STRHImmediate,
    LDRHImmediate,
    LDRSHImmediate64,
    LDRSHImmediate32,
    STRImmediateSIMDFP16,
    LDRImmediateSIMDFP16,
    Unallocated1,
    Unallocated2,
    STRImmediate32,
    LDRImmediate32,
    LDRSWImmediate,
    STRImmediateSIMDFP32,
    LDRImmediateSIMDFP32,
    STRImmediate64,
    LDRImmediate64,
    PRFMImmediate,
    STRImmediateSIMDFP64,
    LDRImmediateSIMDFP64,
}

#[derive(Debug)]
pub struct LoadStoreRegisterUnsignedImmediateData {
    pub size: u32,
    pub v: u32,
    pub opc: u32,
    pub imm12: u32,
    pub rn: u32,
    pub rt: u32,
}
